/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/index.js > TAP > basic > must match snapshot 1`] = `
Object {
  "E": Object {
    "fullname": "East Region",
    "id": "E",
    "name": "East",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 8",
          "seed": 9,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 11",
          "seed": 12,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 10",
          "seed": 11,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 9",
          "seed": 10,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "MW",
    "teams": Array [
      "E Team 0",
      "E Team 1",
      "E Team 2",
      "E Team 3",
      "E Team 4",
      "E Team 5",
      "E Team 6",
      "E Team 7",
      "E Team 8",
      "E Team 9",
      "E Team 10",
      "E Team 11",
      "E Team 12",
      "E Team 13",
      "E Team 14",
      "E Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "FF": Object {
    "championshipName": "National Championship",
    "id": "FF",
    "name": "Final Four",
    "rounds": Array [
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
    ],
  },
  "MW": Object {
    "fullname": "Midwest Region",
    "id": "MW",
    "name": "Midwest",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 8",
          "seed": 9,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 11",
          "seed": 12,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 10",
          "seed": 11,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 9",
          "seed": 10,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "E",
    "teams": Array [
      "MW Team 0",
      "MW Team 1",
      "MW Team 2",
      "MW Team 3",
      "MW Team 4",
      "MW Team 5",
      "MW Team 6",
      "MW Team 7",
      "MW Team 8",
      "MW Team 9",
      "MW Team 10",
      "MW Team 11",
      "MW Team 12",
      "MW Team 13",
      "MW Team 14",
      "MW Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "S": Object {
    "fullname": "South Region",
    "id": "S",
    "name": "South",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 8",
          "seed": 9,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 11",
          "seed": 12,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 10",
          "seed": 11,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 9",
          "seed": 10,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "W",
    "teams": Array [
      "S Team 0",
      "S Team 1",
      "S Team 2",
      "S Team 3",
      "S Team 4",
      "S Team 5",
      "S Team 6",
      "S Team 7",
      "S Team 8",
      "S Team 9",
      "S Team 10",
      "S Team 11",
      "S Team 12",
      "S Team 13",
      "S Team 14",
      "S Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "W": Object {
    "fullname": "West Region",
    "id": "W",
    "name": "West",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 8",
          "seed": 9,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 11",
          "seed": 12,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 10",
          "seed": 11,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 9",
          "seed": 10,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "S",
    "teams": Array [
      "W Team 0",
      "W Team 1",
      "W Team 2",
      "W Team 3",
      "W Team 4",
      "W Team 5",
      "W Team 6",
      "W Team 7",
      "W Team 8",
      "W Team 9",
      "W Team 10",
      "W Team 11",
      "W Team 12",
      "W Team 13",
      "W Team 14",
      "W Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
}
`

exports[`test/index.js > TAP > eliminated > must match snapshot 1`] = `
Object {
  "E": Object {
    "fullname": "East Region",
    "id": "E",
    "name": "East",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
      ],
    ],
    "sameSideAs": "MW",
    "teams": Array [
      "E Team 0",
      "E Team 1",
      "E Team 2",
      "E Team 3",
      "E Team 4",
      "E Team 5",
      "E Team 6",
      "E Team 7",
      "E Team 8",
      "E Team 9",
      "E Team 10",
      "E Team 11",
      "E Team 12",
      "E Team 13",
      "E Team 14",
      "E Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "FF": Object {
    "championshipName": "National Championship",
    "id": "FF",
    "name": "Final Four",
    "rounds": Array [
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "eliminated": true,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "eliminated": true,
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
      ],
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
    ],
  },
  "MW": Object {
    "fullname": "Midwest Region",
    "id": "MW",
    "name": "Midwest",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
      ],
    ],
    "sameSideAs": "E",
    "teams": Array [
      "MW Team 0",
      "MW Team 1",
      "MW Team 2",
      "MW Team 3",
      "MW Team 4",
      "MW Team 5",
      "MW Team 6",
      "MW Team 7",
      "MW Team 8",
      "MW Team 9",
      "MW Team 10",
      "MW Team 11",
      "MW Team 12",
      "MW Team 13",
      "MW Team 14",
      "MW Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "S": Object {
    "fullname": "South Region",
    "id": "S",
    "name": "South",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
      ],
    ],
    "sameSideAs": "W",
    "teams": Array [
      "S Team 0",
      "S Team 1",
      "S Team 2",
      "S Team 3",
      "S Team 4",
      "S Team 5",
      "S Team 6",
      "S Team 7",
      "S Team 8",
      "S Team 9",
      "S Team 10",
      "S Team 11",
      "S Team 12",
      "S Team 13",
      "S Team 14",
      "S Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "W": Object {
    "fullname": "West Region",
    "id": "W",
    "name": "West",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": false,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "eliminated": true,
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
      ],
    ],
    "sameSideAs": "S",
    "teams": Array [
      "W Team 0",
      "W Team 1",
      "W Team 2",
      "W Team 3",
      "W Team 4",
      "W Team 5",
      "W Team 6",
      "W Team 7",
      "W Team 8",
      "W Team 9",
      "W Team 10",
      "W Team 11",
      "W Team 12",
      "W Team 13",
      "W Team 14",
      "W Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
}
`

exports[`test/index.js > TAP > perfect > must match snapshot 1`] = `
Object {
  "E": Object {
    "fullname": "East Region",
    "id": "E",
    "name": "East",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "E",
          "name": "E Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 7",
          "seed": 8,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 4",
          "seed": 5,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 5",
          "seed": 6,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 6",
          "seed": 7,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "MW",
    "teams": Array [
      "E Team 0",
      "E Team 1",
      "E Team 2",
      "E Team 3",
      "E Team 4",
      "E Team 5",
      "E Team 6",
      "E Team 7",
      "E Team 8",
      "E Team 9",
      "E Team 10",
      "E Team 11",
      "E Team 12",
      "E Team 13",
      "E Team 14",
      "E Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "FF": Object {
    "championshipName": "National Championship",
    "id": "FF",
    "name": "Final Four",
    "rounds": Array [
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "E",
          "name": "E Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "E",
            "name": "E Team 0",
            "seed": 1,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
    ],
  },
  "MW": Object {
    "fullname": "Midwest Region",
    "id": "MW",
    "name": "Midwest",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "MW",
          "name": "MW Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 7",
          "seed": 8,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 4",
          "seed": 5,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 5",
          "seed": 6,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 6",
          "seed": 7,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "MW",
          "name": "MW Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "MW",
            "name": "MW Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "E",
    "teams": Array [
      "MW Team 0",
      "MW Team 1",
      "MW Team 2",
      "MW Team 3",
      "MW Team 4",
      "MW Team 5",
      "MW Team 6",
      "MW Team 7",
      "MW Team 8",
      "MW Team 9",
      "MW Team 10",
      "MW Team 11",
      "MW Team 12",
      "MW Team 13",
      "MW Team 14",
      "MW Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "S": Object {
    "fullname": "South Region",
    "id": "S",
    "name": "South",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "S",
          "name": "S Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 7",
          "seed": 8,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 4",
          "seed": 5,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 5",
          "seed": 6,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 6",
          "seed": 7,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "S",
          "name": "S Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "S",
            "name": "S Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "W",
    "teams": Array [
      "S Team 0",
      "S Team 1",
      "S Team 2",
      "S Team 3",
      "S Team 4",
      "S Team 5",
      "S Team 6",
      "S Team 7",
      "S Team 8",
      "S Team 9",
      "S Team 10",
      "S Team 11",
      "S Team 12",
      "S Team 13",
      "S Team 14",
      "S Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
  "W": Object {
    "fullname": "West Region",
    "id": "W",
    "name": "West",
    "rounds": Array [
      Array [
        Object {
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 15",
          "seed": 16,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 7",
          "seed": 8,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 8",
          "seed": 9,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 4",
          "seed": 5,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 11",
          "seed": 12,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 3",
          "seed": 4,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 12",
          "seed": 13,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 5",
          "seed": 6,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 10",
          "seed": 11,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 2",
          "seed": 3,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 13",
          "seed": 14,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 6",
          "seed": 7,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 9",
          "seed": 10,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
        },
        Object {
          "fromRegion": "W",
          "name": "W Team 14",
          "seed": 15,
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 7",
          "seed": 8,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 7",
            "seed": 8,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 4",
          "seed": 5,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 4",
            "seed": 5,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 5",
          "seed": 6,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 5",
            "seed": 6,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 6",
          "seed": 7,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 6",
            "seed": 7,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 3",
          "seed": 4,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 3",
            "seed": 4,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 2",
          "seed": 3,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 2",
            "seed": 3,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 1",
          "seed": 2,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 1",
            "seed": 2,
          },
        },
      ],
      Array [
        Object {
          "correct": true,
          "fromRegion": "W",
          "name": "W Team 0",
          "seed": 1,
          "shouldBe": Object {
            "fromRegion": "W",
            "name": "W Team 0",
            "seed": 1,
          },
        },
      ],
    ],
    "sameSideAs": "S",
    "teams": Array [
      "W Team 0",
      "W Team 1",
      "W Team 2",
      "W Team 3",
      "W Team 4",
      "W Team 5",
      "W Team 6",
      "W Team 7",
      "W Team 8",
      "W Team 9",
      "W Team 10",
      "W Team 11",
      "W Team 12",
      "W Team 13",
      "W Team 14",
      "W Team 15",
    ],
    "winsIn": Array [
      Array [],
      Array [],
      Array [],
      Array [],
      Array [],
    ],
  },
}
`
