name: Run tests

on: [push, pull_request]

jobs:
  data:
    name: Run tests and linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Update npm
        run: |
          npm install -g npm@^7

      - name: Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm test
